In [1]:
import numpy as np


In [2]:
array_1= np.array([(1,2,3),(4,5,6)])
print(array_1)

[[1 2 3]
 [4 5 6]]


In [3]:
array_1.sum()

21

In [4]:
array_2= np.array([(7,8,9),(10,11,12)])

In [5]:
array_3=array_1 + array_2
array_3

array([[ 8, 10, 12],
       [14, 16, 18]])

In [6]:
array_4=array_1 * array_2
array_4

array([[ 7, 16, 27],
       [40, 55, 72]])

In [7]:
array_4.shape

(2, 3)

In [8]:
array_4.size

6

In [9]:
a1=np.random.rand(3,3)
a2=np.random.rand(3,3)
array9=a1*a2
array9

array([[0.25716448, 0.08056039, 0.49257361],
       [0.01267719, 0.21202405, 0.02655888],
       [0.12950523, 0.0160971 , 0.08138241]])

In [10]:
np.linalg.det(array9)

-0.008903267307031247

In [11]:
np.linalg.inv(array9)

array([[-1.89003731, -0.15419164, 11.48992305],
       [-0.2704416 ,  4.81420962,  0.06576831],
       [ 3.06114113, -0.70686282, -6.0094539 ]])

In [12]:
np.sin(a1)

array([[0.272693  , 0.08900597, 0.71897764],
       [0.19826635, 0.24657644, 0.67813165],
       [0.74774757, 0.12385856, 0.16546339]])

In [13]:
np.log(a1)

array([[-1.28666258, -2.41772765, -0.22023497],
       [-1.61149585, -1.38971613, -0.2940792 ],
       [-0.16881724, -2.08604367, -1.79439579]])

In [14]:
c= np.array([[3, 2],[1, 4]]) 
b=np.array([1, 2])
x=np.linalg.solve(c,b)
print(x)

[0.  0.5]


In [15]:

data=np.random.randint(1,101)
print(data)
o=int(input('geb die nummer'))
while data !=o:
    
    if data>o:
        print('die nummer soll gross sein')
    else:
        print('die nummer soll klein sein') 
    o= int(input('die nummer eingeben: '))



        
        

3


geb die nummer 3


In [77]:
e=np.array([[77,40,100],[88,90,55],[53,64,77],[7,80,5],[8,50,90]])
m_men_subject=[]
for x in e:
    print(x)
    

print(np.mean(x))


#print(np.max(x))


#print(np.min(x))


#print(np.std(x))



[ 77  40 100]
[88 90 55]
[53 64 77]
[ 7 80  5]
[ 8 50 90]
49.333333333333336


In [85]:
import numpy as np
 
my_array = np.array([1, 2, 2, 3, 4, 4, 4, 5,5,])
 
counts = np.bincount(my_array)
 
duplicates = np.where(counts > 1)[0]
 
print(" THE NUM IS ", duplicates)

 THE NUM IS  [2 4 5]
